### ISSUE TITLE
Compatible with redis-py 3.x

### ISSUE THREAD

**Issue by dawncold** [closeio/tasktiger#119]
Migration guide
https://github.com/andymccurdy/redis-py#upgrading-from-redis-py-2x-to-30

* found some `zadd` need to change
* Redis -> StrictRedis

**Comment by jkemp101** [comment]
What had to change? We have been using it with Redis 3.x for a while now so would be interested if we missed something.

**Comment by duxiaoyao** [comment]
I think dawncold actually indicates redis-py 3.0 instead of redis 3 as redis-py 3.0 introduces  a number of backwards incompatible changes mentioned in the link which dawncold gives.

**Comment by superbogy** [comment]
Is it in plan? this is a very strong demand.

**Comment by denizdogan** [comment]
`redis>=3` is a pretty hard requirement for the project I'm working on as well. This should be top priority imo.
