### ISSUE TITLE
How is the `Pause queue processing ` work?

### ISSUE THREAD

**Issue by superbogy** [closeio/tasktiger#134]
I can not found any code from source about the document `Pause queue processing `. Is it deprecated ?

**Comment by jkemp101** [comment]
As described [here](https://github.com/closeio/tasktiger#pause-queue-processing) you need to be using the max workers option. Then you can call `set_queue_system_lock()` to stop processing of a queue. That code is [here](https://github.com/closeio/tasktiger/blob/bdf4f3f63943885423d817bf9c75986713677dcc/tasktiger/__init__.py#L380).

**Comment by superbogy** [comment]
@jkemp101 The method of TaskTiger  can not be found in latest version package(v.0.9.4). Is it not release to current pip package?

**Comment by jkemp101** [comment]
That wouldn't be in the 0.9.4 release. Sorry about that. Looks like time has been flying, haven't gotten a release out in a bit. I know of at least one fix I need to look at first but we will try to cut a release soon. We are using the current master in a couple services so it is pretty stable but we still need to ship a new release.

**Comment by superbogy** [comment]
Looking forward to the new release

**Comment by jkemp101** [comment]
[v0.9.5](https://github.com/closeio/tasktiger/releases/tag/v0.9.5) has been released.
