### ISSUE TITLE
setup_structlog = True breaking TaskTiger initialization 

### ISSUE THREAD

**Issue by uniacid** [closeio/tasktiger#140]
Setting setup_structlog to True when initializing TaskTiger in my manage.py is breaking in TaskTiger 0.9.5, ex: `tiger = TaskTiger(setup_structlog=True)`

The root cause seems to be line 201 in __init__.py where it's saying the logging module doesn't have a DEBUG attribute "AttributeError: 'module' object has no attribute 'DEBUG'"
`if setup_structlog:`
`self.log.setLevel(logging.DEBUG)`

Below is my log output:

> 06:55:48 tiger_worker2.1  | Traceback (most recent call last):
> 06:55:48 tiger_worker2.1  |   File "manage.py", line 23, in <module>
> 06:55:48 worker.1         | Traceback (most recent call last):
> 06:55:48 tiger_worker2.1  |     tiger = TaskTiger(setup_structlog=True)
> 06:55:48 worker.1         |   File "manage.py", line 23, in <module>
> 06:55:48 tiger_worker2.1  |   File "/Users/uniacid/Sites/Xivg/cleanse.studio/env/lib/python2.7/site-packages/tasktiger/__init__.py", line 201, in __init__
> 06:55:48 web.1            | Traceback (most recent call last):
> 06:55:48 tiger_worker3.1  | Traceback (most recent call last):
> 06:55:48 cleanse_worker.1 | Traceback (most recent call last):
> 06:55:48 worker.1         |     tiger = TaskTiger(setup_structlog=True)
> 06:55:48 tiger_worker1.1  | Traceback (most recent call last):
> 06:55:48 tiger_worker2.1  |     self.log.setLevel(logging.DEBUG)
> 06:55:48 web.1            |   File "manage.py", line 23, in <module>
> 06:55:48 tiger_worker3.1  |   File "manage.py", line 23, in <module>
> 06:55:48 cleanse_worker.1 |   File "manage.py", line 23, in <module>
> 06:55:48 worker.1         |   File "/Users/uniacid/Sites/Xivg/cleanse.studio/env/lib/python2.7/site-packages/tasktiger/__init__.py", line 201, in __init__
> 06:55:48 tiger_worker1.1  |   File "manage.py", line 23, in <module>
> 06:55:48 tiger_worker2.1  | AttributeError: 'module' object has no attribute 'DEBUG'
> 06:55:48 web.1            |     tiger = TaskTiger(setup_structlog=True)
> 06:55:48 tiger_worker3.1  |     tiger = TaskTiger(setup_structlog=True)
> 06:55:48 cleanse_worker.1 |     tiger = TaskTiger(setup_structlog=True)
> 06:55:48 worker.1         |     self.log.setLevel(logging.DEBUG)
> 06:55:48 tiger_worker1.1  |     tiger = TaskTiger(setup_structlog=True)
> 06:55:48 tiger_worker2.1  | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sentry.io:443
> 06:55:48 web.1            |   File "/Users/uniacid/Sites/Xivg/cleanse.studio/env/lib/python2.7/site-packages/tasktiger/__init__.py", line 201, in __init__
> 06:55:48 tiger_worker3.1  |   File "/Users/uniacid/Sites/Xivg/cleanse.studio/env/lib/python2.7/site-packages/tasktiger/__init__.py", line 201, in __init__
> 06:55:48 cleanse_worker.1 |   File "/Users/uniacid/Sites/Xivg/cleanse.studio/env/lib/python2.7/site-packages/tasktiger/__init__.py", line 201, in __init__
> 06:55:48 worker.1         | AttributeError: 'module' object has no attribute 'DEBUG'
> 06:55:48 tiger_worker1.1  |   File "/Users/uniacid/Sites/Xivg/cleanse.studio/env/lib/python2.7/site-packages/tasktiger/__init__.py", line 201, in __init__
> 06:55:48 web.1            |     self.log.setLevel(logging.DEBUG)
> 06:55:48 tiger_worker3.1  |     self.log.setLevel(logging.DEBUG)
> 06:55:48 cleanse_worker.1 |     self.log.setLevel(logging.DEBUG)
> 06:55:48 worker.1         | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sentry.io:443
> 06:55:48 tiger_worker1.1  |     self.log.setLevel(logging.DEBUG)
> 06:55:48 web.1            | AttributeError: 'module' object has no attribute 'DEBUG'
> 06:55:48 tiger_worker3.1  | AttributeError: 'module' object has no attribute 'DEBUG'
> 06:55:48 cleanse_worker.1 | AttributeError: 'module' object has no attribute 'DEBUG'
> 06:55:48 tiger_worker1.1  | AttributeError: 'module' object has no attribute 'DEBUG'

**Comment by mrname** [comment]
Note that this is only a problem with python 2. With the recent EOL of python 2 I am not certain as to whether this team plans on continuing to support it. If so, I am happy to look into a pull request, but if not, the `setup.py` should be changed to indicate lack of support for 2.X

**Comment by AlecRosenbaum** [comment]
This issue should be fixed with https://github.com/closeio/tasktiger/pull/150

The fix will ship with next release (which should be pretty soon).
