### ISSUE TITLE
Docs: options are unclear

### ISSUE THREAD

**Issue by philfreo** [closeio/tasktiger#15]
Options are unclear because:

- the heading `The following options are supported for delay:` seems to apply to more than just delay
- some options (e.g. unique, lock) don't indicate what data type (e.g. boolean) is expected

**Comment by philfreo** [comment]
options for retry (e.g. exponential) should be made more clear that they are in seconds

**Comment by thomasst** [comment]
- [ ] Make `BATCH_QUEUES` setting clearer
