### ISSUE TITLE
is there any plan to support the Windows platform ?

### ISSUE THREAD

**Issue by thomasleveil** [closeio/tasktiger#156]
Hi, 

In its current state (v0.10.1), this project is not compatible with the Windows platform due to the use of the fcntl module.

Is there any plan to make this project compatible with Windows ?

Also I guess the package descriptions should be fixed to reflect that fact. Currenty setup.py reads:

```python
setup(
    name='tasktiger',
    version='0.10.1',
    ...
    platforms='any',
    ...
    classifiers=[
        'Operating System :: OS Independent',
```

**Comment by AlecRosenbaum** [comment]
I am not aware of any plans to support the windows platform. AFAIK, none of the maintainers run windows so we wouldn't catch any issues. There's a good amount of logic around process management that would probably not work as-is. Changes are typically just tested on Linux and OS X.

I didn't realize the package description indicated windows support, thank you for pointing it out. I'll fix it in with the next release.

cc/ @jkemp101 @thomasst

**Comment by thomasleveil** [comment]
Thank you for that prompt reply. Should we let this opened until the package description get fixed?

**Comment by AlecRosenbaum** [comment]
Yep! I'll close it with the PR that fixed it.

**Comment by AlecRosenbaum** [comment]
`master` has the fix, it'll show up on pypi in the next release.
