### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [closeio/tasktiger#197]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine tests/test_queue_size.py and observe `queing`, however expect to see `queuing`.
- Examine tasktiger/worker.py and observe `requeueing`, however expect to see `requeuing`.
- Examine tasktiger/tasktiger.py and observe `processeses`, however expect to see `processes`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/tasktiger/pull/new/bugfix_typos

Thanks.

**Comment by AlecRosenbaum** [comment]
Done. Thank you!
