### ISSUE TITLE
queue a task from a PHP script?

### ISSUE THREAD

**Issue by vkatochka** [closeio/tasktiger#226]
Hi, there
Is there a way to queue a task from a PHP script? For example, directly insert a record into Redis?

**Comment by AlecRosenbaum** [comment]
It might be possible for simple cases, but I would highly discourage it. The state management system of tasks is relatively complicated, and the data persisted into Redis has been serialized in a format that's not guaranteed to be stable across versions of tasktiger and is not part of the public API.

I'd recommend exposing a private web endpoint from the Python-based service running tasktiger, and calling that web endpoint from the PHP script instead. Then tasktiger can still do the heavy lifting of dealing with task state management, and the PHP<>Tasktiger interface will be stable and more obvious to anyone new to the project.
