### ISSUE TITLE
Support Redis >= 6.2.7 (Lua readonly global tables)

### ISSUE THREAD

**Issue by nsaje** [closeio/tasktiger#268]
On redis >= 6.2.7 we currently encounter an "Attempt to modify a readonly table" error (more info [here](https://github.com/closeio/tasktiger/issues/238))
This error is introduced by https://github.com/redis/redis/pull/10651 which hardened Lua script execution by not allowing modifications of global tables and is affecting Redis versions >= 6.2.7.

It happens because when trying to execute a pipeline using the `execute_pipeline` Lua script, we try to set the `KEYS` and `ARGV` global variables before calling another script using `EVALSHA`.

Executing pipelines via a Lua script was [introduced](https://github.com/closeio/tasktiger/issues/54) because Redis transactions don't abort execution of commands when one of the commands in the transaction fails.

The fix would probably be to use [Redis functions](https://redis.io/docs/manual/programmability/functions-intro/) for Redis 7.0 and above, because they're directly callable by providing `keys` and `argv` in the call itself using `FCALL <func_name> <keys> <argv>`

**Comment by nsaje** [comment]
cc @thomasst , any thoughts on this? 😄

**Comment by thomasst** [comment]
> The fix would probably be to use [Redis functions](https://redis.io/docs/manual/programmability/functions-intro/) for Redis 7.0 and above, because they're directly callable by providing `keys` and `argv` in the call itself using `FCALL <func_name> <keys> <argv>`

I have not played around with Redis 7 but that looks good. The way we're doing it currently is a hack.

**Comment by joeleclems** [comment]
Hi,
For information, we encountered the same problem with redis 6.2.6. We also have redis database in version 6.2.5, and no problems with theses bdd.
So i think the problem is on redis >= 6.2.6
