### ISSUE TITLE
Inconsistent behavior in periodic function

### ISSUE THREAD

**Issue by vishesh10** [closeio/tasktiger#308]
## Description
`periodic` function returns inconsistent results with respect to next execution timestamps. For instance
```
dt = datetime.datetime(2010, 1, 1)
f = periodic(hours=5)
print(f[0](dt, *f[1]))
```
returns `2010-01-01 03:00:00` and 
```
dt = datetime.datetime(2010, 1, 1)
f = periodic(hours=3)
print(f[0](dt, *f[1]))
```
also returns `2010-01-01 03:00:00`

**Comment by AlecRosenbaum** [comment]
I'm not sure what I missing, these look like the same code block to me?

**Comment by vishesh10** [comment]
Apologies for the confusion. I have updated the description.

**Comment by AlecRosenbaum** [comment]
I think it's just a coincidence in the numbers you picked that they come out the same (3 and 5 share a number of multiples)

![image](https://github.com/closeio/tasktiger/assets/1953412/2e2c5095-3057-4afa-896a-2c5c031ec0bf)
