### ISSUE TITLE
TaskImportError in quickstart example

### ISSUE THREAD

**Issue by mdsrosa** [closeio/tasktiger#50]
I'm following the `Quickstart` example described in the README and I'm getting `TaskImportError`:

`tasks.py`:
```
def create_event(data=None):
   print('Create event!')
```

In the terminal:
```
$ ipython
Python 3.5.2 (default, Aug 16 2016, 00:16:44)
IPython 5.1.0 -- An enhanced Interactive Python.

In [1]: import tasktiger, tasks

In [2]: from redis import StrictRedis

In [3]: redis = StrictRedis(host='localhost', port=6379, db=1)

In [4]: tiger = tasktiger.TaskTiger(connection=redis)

In [5]: tiger.delay(tasks.create_event)
Out[5]: <Task <function create_event at 0x10c7047b8>>
```

Worker output:

> {"pid": 81586, "queue": "default", "exception_name": "tasktiger.exceptions.TaskImportError", "task_id": "4762d274dc73a4fd8b1153f98080eb2688eeae89ddd0a88ec972a6efe94d0be1", "func": "tasks.create_event", "traceback": "Traceback (most recent call last):\n  File \"/Users/mrosa/Projects/tasktiger/tasktiger/_internal.py\", line 45, in import_attribute\n    module = importlib.import_module(module_name)\n  File \"/Users/mrosa/.virtualenvs/api/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 956, in _find_and_load_unlocked\nImportError: No module named 'tasks'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/mrosa/Projects/tasktiger/tasktiger/worker.py\", line 206, in _execute_forked\n    func = tasks[0].func\n  File \"/Users/mrosa/Projects/tasktiger/tasktiger/task.py\", line 150, in func\n    self._func = import_attribute(self.serialized_func)\n  File \"/Users/mrosa/Projects/tasktiger/tasktiger/_internal.py\", line 48, in import_attribute\n    raise TaskImportError(e)\ntasktiger.exceptions.TaskImportError: No module named 'tasks'\n", "timestamp": "2017-01-05T15:34:48.259495Z", "time_failed": 1483630488.242499, "level": "error"}

I'm running from the `master` branch with Python 3.5.2 in a virtualenv.

**Comment by thomasst** [comment]
Thanks for reporting this. By default, running `tasktiger` doesn't include the current directory in the `PYTHONPATH`, so you need to make sure it can find the code. I've added a clarification to the README.
