### ISSUE TITLE
Set expiration on redis Lock keys

### ISSUE THREAD

**Issue by jkemp101** [closeio/tasktiger#53]
A redis expiration of lock expiration + a troubleshooting window (i.e. 1 day) should be set on each lock object when it is created and renewed.  This will ensure lock objects are not left orphaned in the Redis store.

**Comment by alanhamlett** [comment]
Would the symptom of this be tasks in state `active` even when workers aren't running?

**Comment by jpmelos** [comment]
We have switched to the lock provided by redis-py and all locks now have an expiration date.
