### ISSUE TITLE
Option to set task expiry time

### ISSUE THREAD

**Issue by dawncold** [closeio/tasktiger#63]
Defines an optional expiry time, the task should not be executed after the expiry time. When a worker receives an expired task it will ignore the task or mark the task  state as **EXPIRED**.

Our scenerio: We need send coupon expriation notification to our customers via E-mail, SMS, etc. The worker should never send the notification when the coupon has already been expired.

**Comment by alanhamlett** [comment]
This could be solved by checking the coupon's expire time in your task before notifying the user. IMO this isn't something that tasktiger should handle.

Let's prevent tasktiger from becoming bloated like Celery?

**Comment by thomasst** [comment]
I agree with @alanhamlett .
