### ISSUE TITLE
Optimize scheduled task queueing

### ISSUE THREAD

**Issue by thomasst** [closeio/tasktiger#89]
When there are many queues, `_worker_queue_scheduled_tasks` is looping through all the scheduled queues after every worker run, which causes a lot of Redis overhead.

**Comment by jkemp101** [comment]
Related code:
https://github.com/closeio/tasktiger/blob/e926d7802cb3caeba0f757852e09feb5f39f16d2/tasktiger/worker.py#L1017-L1023

Some ideas:
* Provide an argument to specify the number of expected workers and do something like `self.config['SELECT_TIMEOUT']  * self.num_workers` to adjust how often it is called based on how many workers will be calling it
* Use [LimitLion](https://github.com/closeio/limitlion) to control how often workers run the related code
* Use a Redis `SETNX` call that creates a key that expires in `SELECT_TIMEOUT`. The worker that wins and sets that key makes the related calls. Need concept of worker group name so we can have a key per group of related workers (this is needed in the LimitLion approach also)

**Comment by jkemp101** [comment]
For the `SETNX` or LimitLion option we could probably just have a key/throttle per root queue and not need a group name.

**Comment by jkemp101** [comment]
@thomasst Should we close this? I don't think we have any further optimizations planned.
