### ISSUE TITLE
Improve Redis Lock

### ISSUE THREAD

**Issue by jkemp101** [closeio/tasktiger#93]
There are a number of improvements that can be made to the existing `redis_lock.Lock`.

* Support a Semaphore locking construct to allow orchestrating multiple workers (added [`redis_semaphore.py`](https://github.com/closeio/tasktiger/blob/master/tasktiger/redis_semaphore.py))
* Renewing fails for non-lock owners
* Include lock ID or other metadata to identify who holds the lock
* Don't leave orphaned keys https://github.com/closeio/tasktiger/issues/53

Update: We most likely just need to switch to the Lock provided in redis-py

**Comment by jpmelos** [comment]
We have switched to the lock provided by redis-py.
