### ISSUE TITLE
Pre/post task execution hooks?

### ISSUE THREAD

**Issue by crolfe** [closeio/tasktiger#95]
Does tasktiger have anything analogous to Celery's `task_prerun` and `task_postrun` signals?  See: http://docs.celeryproject.org/en/latest/userguide/signals.html#task-prerun  

I work on a multi-tenant application that needs to be able to switch databases whenever an asynchronous task runs.  In order to do this in Celery, we place a piece of metadata into the task's kwargs when it is queued, and the pop it off in a handler function when `task_prerun` is fired.  

Assuming this isn't currently available, I think I have an idea how to add a simple version.  Let me know if this is a feature you'd like to see.

**Comment by thomasst** [comment]
There isn't anything currently. How about having a custom task decorator that simply calls the hook before/after the actual task is executed?

**Comment by thomasst** [comment]
Please give feedback here: https://github.com/closeio/tasktiger/pull/105

**Comment by jkemp101** [comment]
I believe we addressed this issue. Feel free to reopen if needed.
